version: "3.8"
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
  db-migration:
    container_name: db_migration
    build: .
    command: >
      bash -c "python manage.py migrate --noinput  && python manage.py collectstatic --noinput"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  web:
    build: .
    command: gunicorn data_foot.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
