# Generated by Django 5.0.1 on 2024-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('squad_size', models.IntegerField()),
                ('average_age', models.FloatField()),
                ('foreigner_percentage', models.FloatField()),
                ('national_teams_players', models.IntegerField()),
                ('stadium_name', models.CharField(max_length=255)),
                ('stadium_seats', models.IntegerField()),
                ('net_transfer_record', models.IntegerField()),
                ('last_season', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
