
# Generated by Django 5.0.1 on 2024-01-12 14:15


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('squad_size', models.IntegerField()),
                ('average_age', models.CharField(max_length=255)),
                ('stadium_name', models.CharField(max_length=255)),
                ('stadium_seats', models.IntegerField()),
                ('net_transfer_record', models.CharField(max_length=255)),
                ('last_season', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
                ('foreigners_number', models.IntegerField()),
                ('foreigners_percentage', models.CharField(max_length=255)),
                ('national_team_players', models.IntegerField()),
                ('coach_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('competition_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('competition_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('domestic_league_code', models.CharField(max_length=100)),
                ('confederation', models.CharField(choices=[('EU', 'europa')], max_length=100)),
                ('url', models.URLField()),
                ('country_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_season', models.IntegerField()),
                ('current_club_id', models.IntegerField()),
                ('player_code', models.CharField(max_length=255)),
                ('country_of_birth', models.CharField(max_length=255)),
                ('city_of_birth', models.CharField(max_length=255)),
                ('country_of_citizenship', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('sub_position', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('foot', models.CharField(max_length=255)),
                ('height_in_cm', models.CharField(max_length=255)),
                ('contract_expiration_date', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('current_club_name', models.CharField(max_length=255)),
                ('market_value_in_eur', models.CharField(max_length=255)),
                ('highest_market_value_in_eur', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('round', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('home_club_goals', models.IntegerField()),
                ('away_club_goals', models.IntegerField()),
                ('home_club_position', models.IntegerField()),
                ('away_club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayClubs', to='django_app_foot.club')),
                ('competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='django_app_foot.competition')),
                ('home_club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeClubs', to='django_app_foot.club')),
            ],
        ),
        migrations.CreateModel(
            name='ClubGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_goals', models.IntegerField()),
                ('own_position', models.FloatField(blank=True, null=True)),
                ('own_manager_name', models.CharField(max_length=100)),
                ('opponent_goals', models.IntegerField()),
                ('opponent_position', models.FloatField(blank=True, null=True)),
                ('opponent_manager_name', models.CharField(max_length=100)),
                ('hosting', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubGames', to='django_app_foot.club')),
                ('opponent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_club', to='django_app_foot.club')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubGames', to='django_app_foot.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('minute', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('club_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('player_in_id', models.IntegerField()),
                ('player_assist_id', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='django_app_foot.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='django_app_foot.player')),
            ],
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('appearance_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('player_club_id', models.IntegerField()),
                ('player_current_club_id', models.IntegerField()),
                ('date', models.DateField()),
                ('player_name', models.CharField(max_length=100)),
                ('competition_id', models.CharField(max_length=100)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearences', to='django_app_foot.game')),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='django_app_foot.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('datetime', models.DateTimeField()),
                ('dateweek', models.DateField()),
                ('market_value_in_eur', models.IntegerField()),
                ('current_clubs_id', models.IntegerField()),
                ('player_club_domestic_competition_id', models.CharField(max_length=100)),
                ('player_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerValuations', to='django_app_foot.player')),
            ],
        ),
    ]
