# Generated by Django 5.0.1 on 2024-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('appearance_id', models.CharField(primary_key=True, serialize=False)),
                ('game_id', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_club_id', models.IntegerField()),
                ('player_current_club_id', models.IntegerField()),
                ('date', models.DateField()),
                ('player_name', models.CharField(max_length=100)),
                ('competition_id', models.CharField(max_length=100)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Club_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('own_position', models.IntegerField()),
                ('own_manager_name', models.CharField(max_length=100)),
                ('opponent_id', models.IntegerField()),
                ('opponent_goals', models.IntegerField()),
                ('opponents_position', models.IntegerField()),
                ('opponent_manager_name', models.CharField(max_length=100)),
                ('hosting', models.CharField(max_length=100)),
            ],
        ),
    ]
