# Generated by Django 5.0.1 on 2024-01-11 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_games',
            old_name='opponent_position',
            new_name='opponents_position',
        ),
    ]
