# Generated by Django 5.0.1 on 2024-01-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club_games',
            old_name='opponents_position',
            new_name='opponent_position',
        ),
        migrations.AlterField(
            model_name='club_games',
            name='own_position',
            field=models.IntegerField(default=0),
        ),
    ]
