# Generated by Django 5.0.1 on 2024-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
