# Generated by Django 5.0.1 on 2024-01-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_code',
            field=models.CharField(max_length=100),
        ),
    ]
