# Generated by Django 5.0.1 on 2024-01-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='domestic_competition_id',
            field=models.IntegerField(default=1),
        ),
    ]
