# Generated by Django 5.0.1 on 2024-01-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0002_club_domestic_competition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='national_teams_players',
            new_name='foreigners_number',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='foreigner_percentage',
            new_name='foreigners_percentage',
        ),
        migrations.AddField(
            model_name='club',
            name='coach_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='national_team_players',
            field=models.IntegerField(null=True),
        ),
    ]
