# Generated by Django 5.0.1 on 2024-01-12 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0002_alter_competition_competition_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='competition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='django_app_foot.competition'),
        ),
    ]
