# Generated by Django 5.0.1 on 2024-01-12 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0003_alter_game_competition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='competition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app_foot.competition'),
        ),
    ]
