# Generated by Django 5.0.1 on 2024-01-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0003_rename_national_teams_players_club_foreigners_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='coach_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='domestic_competition_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='national_team_players',
            field=models.IntegerField(),
        ),
    ]
