# Generated by Django 5.0.1 on 2024-01-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0003_rename_away_club_id_game_away_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_club',
            new_name='away_club_id',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_club',
            new_name='home_club_id',
        ),
        migrations.AlterField(
            model_name='playersvaluation',
            name='current_clubs_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
