# Generated by Django 5.0.1 on 2024-01-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0003_alter_club_games_own_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_games',
            name='opponent_position',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
