# Generated by Django 5.0.1 on 2024-01-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0003_competition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
        migrations.AddField(
            model_name='competition',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
    ]
