# Generated by Django 5.0.1 on 2024-01-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0004_alter_club_coach_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_season', models.IntegerField()),
                ('current_club_id', models.IntegerField()),
                ('player_code', models.CharField(max_length=255)),
                ('country_of_birth', models.CharField(max_length=255)),
                ('city_of_birth', models.CharField(max_length=255)),
                ('country_of_citizenship', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sub_position', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('foot', models.CharField(max_length=255)),
                ('height_in_cm', models.FloatField()),
                ('contract_expiration_date', models.DateField()),
                ('agent_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('current_club_domestic_competition_id', models.IntegerField()),
                ('current_club_name', models.CharField(max_length=255)),
                ('market_value_in_eur', models.FloatField()),
                ('highest_market_value_in_eur', models.FloatField()),
            ],
        ),
    ]
