# Generated by Django 5.0.1 on 2024-02-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0004_rename_away_club_game_away_club_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='domestic_competition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='django_app_foot.competition'),
        ),
    ]
