# Generated by Django 5.0.1 on 2024-01-15 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0005_alter_game_competition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='competition_id',
            new_name='competition',
        ),
    ]
