# Generated by Django 5.0.1 on 2024-01-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0005_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='domestic_competition_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_club_domestic_competition_id',
        ),
    ]
