# Generated by Django 5.0.1 on 2024-02-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0005_club_domestic_competition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='domestic_competition_id',
            new_name='competition',
        ),
    ]
