# Generated by Django 5.0.1 on 2024-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0006_remove_club_domestic_competition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='net_transfer_record',
            field=models.CharField(max_length=255),
        ),
    ]
