# Generated by Django 5.0.1 on 2024-01-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0006_rename_competition_id_game_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_club_id',
            new_name='away_club',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_club_id',
            new_name='home_club',
        ),
    ]
