# Generated by Django 5.0.1 on 2024-02-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0006_rename_domestic_competition_id_club_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='competition',
            new_name='domestic_competition_id',
        ),
    ]
