# Generated by Django 5.0.1 on 2024-01-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0007_rename_away_club_id_game_away_club_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='appearance',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='clubgame',
            old_name='club_id',
            new_name='club',
        ),
        migrations.RenameField(
            model_name='clubgame',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_club',
            new_name='home_club_id',
        ),
        migrations.RenameField(
            model_name='gameevent',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='gameevent',
            old_name='player_id',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='playersvaluation',
            old_name='player_id',
            new_name='player',
        ),
    ]
