# Generated by Django 5.0.1 on 2024-02-05 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0008_rename_domestic_competition_id_club_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='club_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='django_app_foot.clubgame'),
        ),
    ]
