# Generated by Django 5.0.1 on 2024-01-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0008_alter_club_average_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='contract_expiration_date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='height_in_cm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='highest_market_value_in_eur',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='market_value_in_eur',
            field=models.CharField(max_length=255),
        ),
    ]
