# Generated by Django 5.0.1 on 2024-01-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0008_rename_game_id_appearance_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='home_club_id',
            new_name='home_club',
        ),
    ]
