# Generated by Django 5.0.1 on 2024-01-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0009_rename_home_club_id_game_home_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='home_club',
            field=models.IntegerField(),
        ),
    ]
