# Generated by Django 5.0.1 on 2024-02-05 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0009_game_club_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='club_game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='django_app_foot.clubgame'),
        ),
    ]
