# Generated by Django 5.0.1 on 2024-01-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0010_alter_game_home_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='home_club',
            new_name='home_club_id',
        ),
    ]
