# Generated by Django 5.0.1 on 2024-02-05 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0011_alter_game_club_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='club_game',
        ),
    ]
