# Generated by Django 5.0.1 on 2024-01-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0011_rename_home_club_game_home_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_club',
            field=models.IntegerField(),
        ),
    ]
