# Generated by Django 5.0.1 on 2024-02-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0012_remove_game_club_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubgame',
            name='is_win',
            field=models.IntegerField(default=2),
        ),
    ]
