# Generated by Django 5.0.1 on 2024-01-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0012_alter_game_away_club'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_club',
            new_name='away_club_id',
        ),
    ]
