# Generated by Django 5.0.1 on 2024-01-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0013_rename_away_club_game_away_club_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameevent',
            old_name='player',
            new_name='player_id',
        ),
    ]
