# Generated by Django 5.0.1 on 2024-02-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0017_alter_clubgame_is_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='competition_id',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='player_current_club_id',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='player_name',
        ),
        migrations.AddField(
            model_name='appearance',
            name='fk_player_club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_players', to='django_app_foot.clubgame'),
        ),
    ]
