# Generated by Django 5.0.1 on 2024-01-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0017_rename_player_gameevent_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameevent',
            old_name='player_id',
            new_name='player',
        ),
    ]
