# Generated by Django 5.0.1 on 2024-02-07 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0018_remove_appearance_competition_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='fk_player_club_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_players', to='django_app_foot.club'),
        ),
    ]
