# Generated by Django 5.0.1 on 2024-01-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0018_rename_player_id_gameevent_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersvaluation',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playerValuations', to='django_app_foot.player'),
        ),
    ]
