# Generated by Django 5.0.1 on 2024-02-07 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0019_alter_appearance_fk_player_club_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='fk_player_club_id',
            new_name='fk_player_club',
        ),
    ]
