# Generated by Django 5.0.1 on 2024-01-15 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0020_alter_playersvaluation_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersvaluation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerValuations', to='django_app_foot.player'),
        ),
    ]
