# Generated by Django 5.0.1 on 2024-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0020_rename_fk_player_club_id_appearance_fk_player_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='squad_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
