# Generated by Django 5.0.1 on 2024-01-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0021_alter_playersvaluation_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='django_app_foot.player'),
        ),
    ]
