# Generated by Django 5.0.1 on 2024-02-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0021_alter_club_squad_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stadium_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
