# Generated by Django 5.0.1 on 2024-02-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0022_alter_club_stadium_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='foreigners_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='last_season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='national_team_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
