# Generated by Django 5.0.1 on 2024-02-07 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0023_alter_club_foreigners_number_alter_club_last_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='django_app_foot.competition'),
        ),
    ]
