# Generated by Django 5.0.1 on 2024-01-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0026_rename_opponent_id_clubgame_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubgame',
            name='opponent',
            field=models.IntegerField(),
        ),
    ]
