# Generated by Django 5.0.1 on 2024-01-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app_foot', '0027_alter_clubgame_opponent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubgame',
            old_name='opponent',
            new_name='opponent_id',
        ),
    ]
